[package]
name = "catmodoro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0"
tui = { version = "0.16", features = ["crossterm"] }
crossterm = "0.23"